### ISSUE TITLE
Can not use push notifications after resign

### ISSUE THREAD

**Issue by xautmini** [maciekish/iReSign#16]
Dear Team：
Thank you very much to bring us such a convenient tool，Recently I encountered a problem  that is my app registration remote push message  with the following error after using iresign:

"no valid 'aps-environment' entitlement string found for application”

I can assure my bundle id and certificates are no problem, because when I test them  in Xcode which  can be registered success

Could you  please tell me what the problem is,and  how to solve? Thanks again。

**Comment by Dershowitz011** [comment]
Does this work only for paid dev account or can I use a paid cert and profile to get notifications?

**Comment by antonkashpor** [comment]
@lizhuext hi, how did you resolve the issue? 
thanks

**Comment by lizhuext** [comment]
Hi，You should  generate an entitlements.plist file and then importing into iresign when resigning. About how to generate this file you can refer xiaolianggit’s answer Or you can refer to Google search. I think there are many answers.
