### ISSUE TITLE
Command line support for iResign

### ISSUE THREAD

**Issue by venkatesh1977** [maciekish/iReSign#20]
The Current version of iResign is GUI based but it will not support command line version.
When can you incorporate command line version of iResign tool?
Through command line version, we can pass the argument to this tool so that anybody can automate this tool base on the usage.

**Comment by djwgit** [comment]
@guangmingwan,  it will be very helpful if you could merge recent changes into your command-line version... thanks.

@maciekish,   nice to re-open this issue.   cli is useful when need to do re-signing within an automated process. thanks for making this tool !
