### ISSUE TITLE
way to change bundle display name

### ISSUE THREAD

**Issue by amit-metkar** [maciekish/iReSign#4]
Hi,

Thanks you so much for the solution to change the bundle Id and re-sign ipa file.

I was trying to find out the way to change the bundle display name with it and then re-sign the ipa file. I'm quite new to the programming language used in the solution. Can you please help me out here, thanks in advance.

-Amit

**Comment by Dershowitz011** [comment]
But by doing so, the CFBundleName changes alright. But when I install on my iPhone, the display name doesn't change at all. Do help. Thanks.
