### ISSUE TITLE
Support for multiple keychains

### ISSUE THREAD

**Issue by tposch** [maciekish/iReSign#5]
I manage both our enterprise account and our non-enterprise account at my company. In my 'login' (default) keychain, I have two certificates with the same common name: "iPhone Distribution: {company name}".

After a little trial and error and research, one resolution seems to be to save the enterprise certificate in a different keychain. I created a new keychain called "enterprise" and it is located at "/Users/tposche/Library/Keychains/enterprise.keychain".

I hard coded the path in the iReSign app temporarily to make sure it would work (it did). This will work for my purposes, but I thought perhaps you might want to add support for this by merely adding a new optional text field for "Keychain Path" or something similar.

Here is the code:

``` objc
NSString *keychainArgument = [NSString stringWithFormat:@"--keychain=%@", @"/Users/tposche/Library/Keychains/enterprise.keychain"];
```

**Comment by KevinGaudin** [comment]
I would love to see that happen too ! :+1:
