### ISSUE TITLE
Signing failed - main executable failed strict validation

### ISSUE THREAD

**Issue by kashban** [maciekish/iReSign#57]
I am using iReSign for the first time and ran into this problem:

/var/folders/yt/xf2qbkr90vg76ns93nkw_jl00000gn/T/com.appulize.iresign/Payload/TIBCO JasperMobile.app: main executable failed strict validation

Any idea how to solve this?

**Comment by dnau** [comment]
Hi,

I have the same problem. Have you or anyone solved it?

**Comment by kashban** [comment]
The issue was with a non aligned (PIE) main executable in the IPA I tried to resign. Having fixed this the issue went away. Also resigning included swift dylibs helped.

**Comment by maciekish** [comment]
Does this mean the issue is not in iReSign?

**Comment by kashban** [comment]
I am not quite sure, since I had multiple issues (missing Entitlements, Swift-libs false signing, bad executable). I need to resign the IPA again anyway, so I'll check this out with the latest version of iResign.

**Comment by kashban** [comment]
I don't think this is a iReSign issue because the same error came up with other tools and while manually codesigning the IPA. It seems to be related with an incorrect app wrapping (BES).

**Comment by maciekish** [comment]
@kashban Did you build your app using Xcode 6.x on the El Capitan beta? I head reports of corrupt builds resulting from that particular combination.

**Comment by kashban** [comment]
No, I got the IPA from a customer, already wrapped with Blackberry Enterprise Security Wrapper. When building the wrapped app on my own, this error inparticular didn't come up. I guess it's an issue with the wrapping process.
