### ISSUE TITLE
I have an IPA which was signed by a distribution certificate. I wish to resign and dont update the bundle ID using the ipa_sign tool. Is that possible?

### ISSUE THREAD

**Issue by XieFreeGeek** [maciekish/iReSign#68]
I have an IPA which was signed by a distribution certificate. I wish to resign and dont update the bundle ID using the ipa_sign tool. Is that possible?

**Comment by maciekish** [comment]
Yes. Changing the id is optional.

**Comment by XieFreeGeek** [comment]
example: before my signature ipa bundleid is com. ABC. I choose to bbb.mobileprovision file com. EDF,So can I put my signature after the ipa bundleid into com. ABC?
