### ISSUE TITLE
resign with apple store .ipa

### ISSUE THREAD

**Issue by TheTechBee** [maciekish/iReSign#73]
Hi Folks,
I am trying to resign an apple store .ipa with my developer certificate using iResign. It resigns the .ipa but does not install on iPad. Any idea why it's not working?

Regards
Ranjan

**Comment by maciekish** [comment]
Because thats not what it was designed for.

**Comment by TheTechBee** [comment]
Thanks for your reply.
Just curious to know is this possible?

**Comment by maciekish** [comment]
Certainly is, but Im not making it public because of piracy concerns.
