### ISSUE TITLE
Implementation Question - File copying

### ISSUE THREAD

**Issue by costonb** [maciekish/iReSign#78]
I have forked your project and am making modifications that my company needs during resigning such as changing out icons and various info.plist entries.  I come from iOS dev and am not as familiar with mac dev.

I noticed when you copy the provisioning profile you are using an NSTask that does /bin/cp instead of just using NSFileManager.  I was wondering if there is a reason for this I should be aware of when copying icons or other assets or if this was just a design choice and doesn't matter as much.

I was not sure of the best place to ask you about this.  Sorry if this is not the right place for this kind of question.

Here is the code I am referring to:

```
provisioningTask = [[NSTask alloc] init];
[provisioningTask setLaunchPath:@"/bin/cp"];
[provisioningTask setArguments:[NSArray arrayWithObjects:[provisioningPathField stringValue], targetPath, nil]];

[provisioningTask launch];

[NSTimer scheduledTimerWithTimeInterval:1.0 target:self selector:@selector(checkProvisioning:) userInfo:nil repeats:TRUE];
```

instead of just something like 

```
NSError *error = nil;
[[NSFileManager defaultManager] copyItemAtPath:[provisioningPathField stringValue] toPath:targetPath error:&error];

[self checkProvisioning];
```

**Comment by maciekish** [comment]
No reason. This project is from the time when i was still learning the ropes :)

**Comment by costonb** [comment]
alright, cool. Thanks for the quick reply!
