### ISSUE TITLE
Getting Certificate ID's failed"

### ISSUE THREAD

**Issue by Parigi65** [maciekish/iReSign#85]
I receive this error when I open iResign.
If I write the name of the Certificate inside the field all goes correctly.

It worked good previously, how I can resolve?
Have I to check something into my Keychain?

Please, help me.

**Comment by diogenesmarchena** [comment]
I'm having the same issue. 

My certificates are not appearing on the dropdown menu.

Is this getting resolved shortly?

**Comment by costonb** [comment]
I was having the same issue.  It's due to an apple certificate expiring.  See this article for details
https://developer.apple.com/support/certificates/expiration/
Following the steps in What should I do if Xcode doesn’t recognize my distribution certificate? fixed this issue for me.

**Comment by Parigi65** [comment]
Thanks! The issue is fixed.
